/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "matrix.h"
#include "numbers.h"

int main(void)
{
    RCC_AHB1ENR_t volatile *clockEnable = (RCC_AHB1ENR_t*)0x40023830;

    GPIOx_MODER_t *gpio_a_mode = (GPIOx_MODER_t*)0x40020000;
    GPIOx_ODR_t *gpio_a_output = (GPIOx_ODR_t*)0x40020014;

    GPIOx_MODER_t *gpio_c_mode = (GPIOx_MODER_t*)0x40020800;
    GPIOx_ODR_t *gpio_c_output = (GPIOx_ODR_t*)0x40020814;
    GPIOx_IDR_t *gpio_c_input = (GPIOx_IDR_t*)0x40020810;

    GPIOx_PUPDR_t *gpio_pullup = (GPIOx_PUPDR_t*)0x4002080C;

    clockEnable->GPIOA_EN = 1; // Enable GPIOA clock
    clockEnable->GPIOC_EN = 1; // Enable GPIOB clock
    enableDisplayGPIO(gpio_a_mode);
    enableMatrix(gpio_c_mode, gpio_pullup);


    while(1)
    {
      initMatrix(gpio_c_output);
      gpio_c_output->PIN_0 = 0;
      if(!(gpio_c_input->PIN_4 & 0x1))
      {
        one(gpio_a_output);
      }
      if(!(gpio_c_input->PIN_5 & 0x1))
      {
        two(gpio_a_output);
      }
      if(!(gpio_c_input->PIN_6 & 0x1))
      {
        three(gpio_a_output);
      }
      if(!(gpio_c_input->PIN_8 & 0x1))
      {
        letter_a(gpio_a_output);
      }
      
      initMatrix(gpio_c_output);
      gpio_c_output->PIN_1 = 0;
      if(!(gpio_c_input->PIN_4 & 0x1))
      {
        four(gpio_a_output);
      }
      if(!(gpio_c_input->PIN_5 & 0x1))
      {
        five(gpio_a_output);
      }
      if(!(gpio_c_input->PIN_6 & 0x1))
      {
        six(gpio_a_output);
      }
      if(!(gpio_c_input->PIN_8 & 0x1))
      {
        letter_b(gpio_a_output);
      }

      initMatrix(gpio_c_output);
      gpio_c_output->PIN_3 = 0;
      if(!(gpio_c_input->PIN_4 & 0x1))
      {
        seven(gpio_a_output);
      }
      if(!(gpio_c_input->PIN_5 & 0x1))
      {
        eight(gpio_a_output);
      }
      if(!(gpio_c_input->PIN_6 & 0x1))
      {
        nine(gpio_a_output);
      }
      if(!(gpio_c_input->PIN_8 & 0x1))
      {
        letter_c(gpio_a_output);
      }

      initMatrix(gpio_c_output);
      gpio_c_output->PIN_2 = 0;
      if(!(gpio_c_input->PIN_4 & 0x1))
      {
        star(gpio_a_output);
      }
      if(!(gpio_c_input->PIN_5 & 0x1))
      {
        zero(gpio_a_output);
      }
      if(!(gpio_c_input->PIN_6 & 0x1))
      {
        hash(gpio_a_output);
      }
      if(!(gpio_c_input->PIN_8 & 0x1))
      {
        letter_d(gpio_a_output);
      }
    }
}
