/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "matrix.h"
#include "numbers.h"

int main(void)
{
    RCC_AHB1ENR_t volatile *clockEnable = (RCC_AHB1ENR_t*)0x40023830;
    GPIOx_MODER_t volatile *gpio_a_mode = (GPIOx_MODER_t*)0x40020000;
    GPIOx_MODER_t volatile *gpio_b_mode = (GPIOx_MODER_t*)0x40020400;
    GPIOx_ODR_t volatile *gpio_a_output = (GPIOx_ODR_t*)0x40020014;
    GPIOx_ODR_t volatile *gpio_b_output = (GPIOx_ODR_t*)0x40020414;
    GPIOx_IDR_t volatile *gpio_b_input = (GPIOx_IDR_t*)0x40020410;
    GPIOx_PUPDR_t volatile *gpio_pullup = (GPIOx_PUPDR_t*)0x4002040C;

    clockEnable->GPIOA_EN = 1; // Enable GPIOA clock
    clockEnable->GPIOB_EN = 1; // Enable GPIOB clock
    enableDisplayGPIO((GPIOx_MODER_t*)&gpio_a_mode);
    enableMatrix((GPIOx_MODER_t*)&gpio_b_mode, (GPIOx_PUPDR_t*)&gpio_pullup);

    while(1)
    {
		uint8_t status = (uint8_t)(gpio_b_input->PIN_0 & 0x1);  // Give state to variable
		if(status)
		{
			two((GPIOx_ODR_t*)&gpio_a_output);
		}else
		{
			clear((GPIOx_ODR_t*)&gpio_a_output);
		}
    }
}
