/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    uint32_t *pGPIO_Clock = (uint32_t*)0x40023800 + 0x30;
    uint32_t *pGPIOA_Mode = (uint32_t*)0x40020000;
    uint32_t *pGPIO_AFRL = (uint32_t*)0x40020000 + 0x20;

    uint32_t *pTIM_CLOCK = (uint32_t*)0x40023800 + 0x40;
    uint32_t *pCLOCK_config = (uint32_t*)0x40023800 + 0x08;

    uint32_t *pTIM3_CR1 = (uint32_t*)0x40000400;
    uint32_t *pTIM3_PSC = (uint32_t*)0x40000400 + 0x28;
    uint32_t *pTIM3_ARR = (uint32_t*)0x40000400 + 0x2C;
    uint32_t *pTIM3_CNT = (uint32_t*)0x40000400 + 0x24;
    uint32_t *pTIM3_CCMR1 = (uint32_t*)0x40000400 + 0x18;
    uint32_t *pTIM3_CCER = (uint32_t*)0x40000400 + 0x20;
    uint32_t *pTIM3_CCR1 = (uint32_t*)0x40000400 + 0x34;

    *pGPIO_Clock |= 0x01; // Enable Clock for GPIOA
    *pGPIOA_Mode |= 0x2; //Enable GPIOA PIN 0 to alternate MODE
    *pGPIO_AFRL |= 0x2; //Enable Alternate Function 2 (AF2) which is General Timer to pin 0

    *pTIM_CLOCK |= 0x02; //Enable clock for tim3
    *pTIM3_PSC = 16 - 1;
    *pTIM3_ARR = 2000;
    *pTIM3_CNT = 0;
    *pTIM3_CCMR1 = 0x0060;
    *pTIM3_CCER |= 0x1;
    *pTIM3_CCR1 = 500;

    *pCLOCK_config |= 0<<10;
    *pTIM3_CR1 |= 0x1;
    
}